// Copyright Epic Games, Inc. All Rights Reserved.


#include "TP_WeaponComponent.h"

//#include "EnemyBase.h"
//#include "EnemyPoolManager.h"
#include "Ludens_PCharacter.h"
#include "Ludens_PProjectile.h"
#include "GameFramework/PlayerController.h"
#include "Camera/PlayerCameraManager.h"
#include "Kismet/GameplayStatics.h"
#include "EnhancedInputComponent.h"
#include "EnhancedInputSubsystems.h"
#include "JellooComponent.h"
#include "PlayerState_Real.h"
#include "Net/UnrealNetwork.h"
#include "Projects.h"
#include "Animation/AnimInstance.h"
#include "Camera/CameraComponent.h"
#include "Engine/LocalPlayer.h"
#include "Engine/World.h"

// Sets default values for this component's properties
// ë¬´ê¸° ì¢…ë¥˜ì™€ Fire ë©”ì„œë“œ, Jelloo í¡ìˆ˜ ë“± ë¬´ê¸°ì™€ ê´€ë ¨ëœ ë©”ì„œë“œë“¤
UTP_WeaponComponent::UTP_WeaponComponent()
{
	// Default offset from the character location for projectiles to spawn
	MuzzleOffset = FVector(50.0f, 100.0f, 0.0f);
}

void UTP_WeaponComponent::BeginPlay()
{
	Super::BeginPlay();

	if (!Character)
	{
		Character = Cast<ALudens_PCharacter>(GetOwner());
		if (!Character)
		{
			UE_LOG(LogTemp, Error, TEXT("WeaponComponent could not find owning character!"));
		}
	}
}

void UTP_WeaponComponent::Fire()
{
	// ìœ„ì¹˜ ë° ë°©í–¥
	APlayerController* PC = Cast<APlayerController>(Character->GetController());
	if (!PC) return;
	FRotator SpawnRotation = PC->PlayerCameraManager->GetCameraRotation();
	
	// Pitch ë³´ì •ìš© ì¿¼í„°ë‹ˆì–¸ ìƒì„±(ìœ„ìª½ìœ¼ë¡œ 7ë„ íšŒì „)
	FQuat PitchAdjustment = FQuat(Character->GetActorRightVector(), FMath::DegreesToRadians(-7.0f));

	// íšŒì „ ì¿¼í„°ë‹ˆì–¸ì— ë³´ì • ê³±í•˜ê¸°
	FQuat SpawnQuat = SpawnRotation.Quaternion();
	SpawnQuat = PitchAdjustment * SpawnQuat;

	// ë‹¤ì‹œ Rotatorë¡œ ë³€í™˜
	SpawnRotation = SpawnQuat.Rotator();
	
	// ì´êµ¬ ì•ìª½ì—ì„œ ë°œì‚¬
	constexpr float Distance = 30.0f;
	FVector FireDirection = SpawnRotation.Vector();
	FVector SpawnLocation = GetMuzzleLocation() + FireDirection * Distance;
	
	if (Character->HasAuthority())
	{
		HandleFire(SpawnLocation, SpawnRotation);
	}
	else
	{
		ServerFire(SpawnLocation, SpawnRotation);
	}
}
void UTP_WeaponComponent::ServerFire_Implementation(FVector_NetQuantize SpawnLocation, FRotator SpawnRotation)
{
	// í´ë¼ì´ì–¸íŠ¸ê°€ ìš”ì²­ â†’ ì„œë²„ì—ì„œ ì²˜ë¦¬
	HandleFire(SpawnLocation, SpawnRotation);
}
void UTP_WeaponComponent::HandleFire(const FVector& SpawnLocation, const FRotator& SpawnRotation) //ì„œë²„ì—ì„œ ì“°ëŠ” Fire (ì–˜ê°€ ì§„ì§œ Projectileì„ ì˜ëŠ”ê±°ì„)
{
	bIsWeaponAttacking = true; // ê³µê²© í–ˆë‹¤ëŠ” ê±¸ boolíƒ€ì…ìœ¼ë¡œ í‘œì‹œ
	
	if (!ProjectileClass) //í”„ë¡œì íƒ€ì¼ nullê°’ ë°©ì§€
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ ProjectileClass is null"));
		return;
	}

	if (!Character) //ìºë¦­í„° nullê°’ ë°©ì§€
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ Character is null in HandleFire"));
		return;
	}

	FActorSpawnParameters SpawnParams;
	SpawnParams.Owner = GetOwner();
	SpawnParams.Instigator = Cast<APawn>(GetOwner());
	//SpawnParams.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AdjustIfPossibleButDontSpawnIfColliding;
	SpawnParams.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AdjustIfPossibleButAlwaysSpawn;


	ALudens_PProjectile* Projectile = GetWorld()->SpawnActor<ALudens_PProjectile>(ProjectileClass, SpawnLocation, SpawnRotation, SpawnParams); // (ìŠ¤í° ìœ„ì¹˜, ë°©í–¥, ì•¡í„°ê°€ ê²Œì„ ì›”ë“œê°€ ìŠ¤í°ë  ë•Œ ë””í…Œì•Œí•œ ë¶€ë¶„ì„ ì¡°ì • ê°€ëŠ¥.)
	if (!Projectile)
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ Projectile spawn failed"));
		return;
	}

	// ğŸ”Š ì„œë²„ì—ì„œë„ ì‚¬ìš´ë“œ/ì• ë‹ˆë©”ì´ì…˜ ì¬ìƒì€ Multicast ë˜ëŠ” í´ë¼ ì „ìš©ìœ¼ë¡œ ì²˜ë¦¬ í•„ìš”

	if (FireSound)
	{
		UGameplayStatics::PlaySoundAtLocation(this, FireSound, Character->GetActorLocation());
	}

	if (WeaponAttackMontage)
	{
		PlayMontage(WeaponAttackMontage, 1.0f);
	}
	// ì•ˆì „í•˜ê²Œ ìºìŠ¤íŒ…í•˜ì—¬ í• ë‹¹
	PSR = Cast<APlayerState_Real>(Cast<ACharacter>(GetOwner())->GetPlayerState());

	if (!PSR)
	{
		UE_LOG(LogTemp, Error, TEXT("[PlayerStateComponent] PSR is nullptr! in HandleFire"));
		return;
	}
	
	GetWorld()->GetTimerManager().SetTimer(WeaponAttackTimer, this, &UTP_WeaponComponent::EndWeaponAttack, PSR->WeaponAttackCoolTime, false); // ë¬´ê¸° ê³µê²© ì¿¨íƒ€ì„ ì ìš©
}

void UTP_WeaponComponent::EndWeaponAttack()
{
	bIsWeaponAttacking = false;
}

FVector UTP_WeaponComponent::GetMuzzleLocation() const
{
	// ì´êµ¬ì˜ ìœ„ì¹˜ ê³„ì‚°
	if (AActor* OwnerActor = GetOwner())
	{
		// ì´ë¦„ì´ Muzzleì¸ StaticMeshComponent ë¨¼ì € ì°¾ê¸°
		TArray<UStaticMeshComponent*> MeshComponents;
		OwnerActor->GetComponents<UStaticMeshComponent>(MeshComponents);
		for (UStaticMeshComponent* Comp : MeshComponents)
		{
			if (Comp && Comp->GetName() == TEXT("Muzzle"))
			{
				return Comp->GetComponentLocation();
			}
		}
	}
	// ì—†ìœ¼ë©´ ìì²´ ìœ„ì¹˜ ë°˜í™˜ (ì•ˆì „ fallback)
	return GetComponentLocation();
}

void UTP_WeaponComponent::ServerAbsorb_Implementation()
{
	HandleAbsorb();
}

void UTP_WeaponComponent::HandleAbsorb()
{
	// ë°˜ë“œì‹œ ì„œë²„ì—ì„œë§Œ ë¡œì§ ì‹¤í–‰
	if (!GetOwner() || !GetOwner()->HasAuthority())
	{
		ServerAbsorb();
		return;
	}

	ALudens_PCharacter* Ludens_PCharacter = Cast<ALudens_PCharacter>(Character);
	if (!Ludens_PCharacter)
	{
		UE_LOG(LogTemp, Error, TEXT("OwnerCharacter is not ALudens_PCharacter!"));
		return;
	}
		
	// í™”ë©´ ì¤‘ì‹¬ì—ì„œ ì›”ë“œ ë°©í–¥ êµ¬í•˜ê¸°
	FVector WorldLocation = Ludens_PCharacter->GetFirstPersonCameraComponent()->GetComponentLocation();
	FRotator CameraRotation = Character->GetActorRotation();
	if (APlayerController* PC = Cast<APlayerController>(Character->GetController()))
	{
		CameraRotation = PC->PlayerCameraManager->GetCameraRotation();
	}

	// íŠ¸ë ˆì´ìŠ¤ ì‹œì‘/ë ìœ„ì¹˜ ê³„ì‚°
	FVector TraceDirection = CameraRotation.Vector();
	FVector TraceStart = WorldLocation;
	FVector TraceEnd = TraceStart + (TraceDirection * AbsorbRange);

	// ë¼ì¸ íŠ¸ë ˆì´ìŠ¤
	FHitResult Hit;
	FCollisionQueryParams Params;
	Params.AddIgnoredActor(Character);

	// ë¼ì¸ íŠ¸ë ˆì´ìŠ¤ë¥¼ í•˜ì—¬ ë¬´ì–¸ê°€ì— ë§ì•˜ëŠ”ì§€ë¥¼ ë‚˜íƒ€ëƒ„
	bool bHit = Character->GetWorld()->LineTraceSingleByChannel(Hit, TraceStart, TraceEnd, ECC_Pawn, Params);
	
	// ì•ˆì „í•˜ê²Œ ìºìŠ¤íŒ…í•˜ì—¬ í• ë‹¹
	PSR = Cast<APlayerState_Real>(Cast<ACharacter>(GetOwner())->GetPlayerState());

	if (!PSR)
	{
		UE_LOG(LogTemp, Error, TEXT("[PlayerStateComponent] PSR is nullptr! in HandleAbsorb"));
		return;
	}
	
	// 6. CreatureCombatComponentê°€ ìˆìœ¼ë©´ ë°ë¯¸ì§€ ì ìš©
	if (bHit && Hit.GetActor())
	{
		// ë§ì€ ì•¡í„°ê°€ JellooCompë¥¼ ê°€ì§€ê³  ìˆëŠ”ì§€ ê²€ì‚¬;
		if (UJellooComponent* JellooComp = Hit.GetActor()->FindComponentByClass<UJellooComponent>())
		{
			TargetJelloo = JellooComp;
			// íƒ€ì´ë¨¸ê°€ ì´ë¯¸ ì‘ë™ ì¤‘ì¸ì§€ ë¨¼ì € í™•ì¸
			if (!GetWorld()->GetTimerManager().IsTimerActive(AbsorbDelayTimer))
			{
				GetWorld()->GetTimerManager().SetTimer(AbsorbDelayTimer, this, &UTP_WeaponComponent::PerformAbsorb, AbsorbDelay, false);
			}
		}
	}
	else
	{
		UE_LOG(LogTemp, Error, TEXT("<UNK> Absorb failed"));
		StopPerformAbsorb();
		return;
	}
}

void UTP_WeaponComponent::PerformAbsorb()
{
	if (!TargetJelloo)
	{
		// íƒ€ê²Ÿì´ ì—†ìœ¼ë©´ íƒ€ì´ë¨¸ë¥¼ ì¤‘ì§€í•˜ê±°ë‚˜ ë¬´ì‹œ
		GetWorld()->GetTimerManager().ClearTimer(AbsorbDelayTimer);
		return;
	}
	PlayMontage(AbsorbMontage, 1.f);
	TargetJelloo->JellooTakeDamage(AbsorbAmount);
	Character->SavedAmmo += AbsorbAmount;
}

void UTP_WeaponComponent::StopPerformAbsorb()
{
	UE_LOG(LogTemp, Error, TEXT("StopPerformAbsorb"));
	TargetJelloo = nullptr;
	GetWorld()->GetTimerManager().ClearTimer(AbsorbDelayTimer);
}

void UTP_WeaponComponent::EndPlay(const EEndPlayReason::Type EndPlayReason) //í•„ìš” ì—†ì„ê±°ê°™ì€ë°
{
	if (Character == nullptr)
	{
		return;
	}

	if (APlayerController* PlayerController = Cast<APlayerController>(Character->GetController()))
	{
		if (UEnhancedInputLocalPlayerSubsystem* Subsystem = ULocalPlayer::GetSubsystem<UEnhancedInputLocalPlayerSubsystem>(PlayerController->GetLocalPlayer()))
		{
			Subsystem->RemoveMappingContext(FireMappingContext);
		}
	}
}

void UTP_WeaponComponent::PlayMontage_Implementation(UAnimMontage* Montage, float PlaySpeed)
{
	ACharacter* OwnerChar = Cast<ACharacter>(GetOwner());
	if (!OwnerChar)
	{
		UE_LOG(LogTemp, Error, TEXT("OwnerChar is nullptr!"));
		return;
	};
	UAnimInstance* AnimInstance = OwnerChar->GetMesh() ? OwnerChar->GetMesh()->GetAnimInstance() : nullptr;
	if (!AnimInstance)
	{
		UE_LOG(LogTemp, Error, TEXT("AnimInstance is nullptr!"));
		return;
	}
	if (AnimInstance && Montage)
	{
		AnimInstance->Montage_Play(Montage, PlaySpeed);
	}
}

void UTP_WeaponComponent::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const
{
	Super::GetLifetimeReplicatedProps(OutLifetimeProps);
	DOREPLIFETIME(UTP_WeaponComponent, AbsorbAmount);
	
}
