// Fill out your copyright notice in the Description page of Project Settings.

#include "PlayerStateComponent.h"
#include "PlayerState_Real.h"
#include "GameFramework/Character.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "TimerManager.h"
#include "Net/UnrealNetwork.h"
#include "Ludens_P/Ludens_PGameMode.h"


// Sets default values for this component's properties
UPlayerStateComponent::UPlayerStateComponent()
{
	PrimaryComponentTick.bCanEverTick = true;
	SetIsReplicatedByDefault(true); // ì»´í¬ë„ŒíŠ¸ ë³µì œë¥¼ í™œì„±í™”í•©ë‹ˆë‹¤.
}


// Called when the game starts
void UPlayerStateComponent::BeginPlay()
{
	Super::BeginPlay();

	Character = Cast<ACharacter>(GetOwner());
}

void UPlayerStateComponent::TickComponent(float DeltaTime, enum ELevelTick TickType,
	FActorComponentTickFunction* ThisTickFunction)
{
	Super::TickComponent(DeltaTime, TickType, ThisTickFunction);

	if (!bPSRInitialized)
	{
		AActor* Owner = GetOwner();
		if (!Owner) return;

		APawn* Pawn = Cast<APawn>(Owner);
		if (!Pawn) return;

		PSR = Cast<APlayerState_Real>(Pawn->GetPlayerState());
		
		if (PSR)
		{
			CurrentHP = PSR->MaxHP;
			CurrentShield = PSR->MaxShield;
			MoveSpeed = PSR->MoveSpeed;
			CalculateMoveSpeed = MoveSpeed;

			if (Character)
			{
				// ì´ ì»´í¬ë„ŒíŠ¸ê°€ ë¶€ì°©ëœ ìºë¦­í„°ì˜ ì´ˆê¸° ì´ë™ ì†ë„ë¥¼ ì„¤ì •í•©ë‹ˆë‹¤.
				// OnRep_MoveSpeedê°€ ì´ˆê¸°ê°’ì— ëŒ€í•´ í˜¸ì¶œë  ìˆ˜ ìˆìœ¼ë¯€ë¡œ í´ë¼ì´ì–¸íŠ¸ì—ì„œë„ í•„ìš”í•©ë‹ˆë‹¤.
				Character->GetCharacterMovement()->MaxWalkSpeed = MoveSpeed;
			}
			
			///

			if (GetOwnerRole() == ROLE_Authority && PSR)
			{
				PlayerColor = PSR->PlayerColor; 
			}

			///



			bPSRInitialized = true;  // í•œ ë²ˆë§Œ ì‹¤í–‰ë˜ë„ë¡
		}
	}
	// ë‹¤ë¥¸ Tick ë¡œì§ì—ì„œë„ PSRì„ ì ‘ê·¼í•˜ëŠ” ê²½ìš°
	if (!PSR) return;
    
	// ì´í›„ ì•ˆì „í•˜ê²Œ PSR ë©¤ë²„ ì‚¬ìš© ê°€ëŠ¥
}


void UPlayerStateComponent::OnRep_PlayerColor()
{
	//
}


void UPlayerStateComponent::Multicast_PlayKnockedUI_Implementation()
{
	if (ACharacter* Char = Cast<ACharacter>(GetOwner()))
	{
		if (Char->IsLocallyControlled())
		{
			DamageVignetteOpacity = 1.0f; 
			// ğŸ’¥ ì¼ë°˜ ë°ë¯¸ì§€ íƒ€ì´ë¨¸ê°€ ì‹¤í–‰ ì¤‘ì´ë”ë¼ë„ ë©ˆì¶¥ë‹ˆë‹¤.
			GetWorld()->GetTimerManager().ClearTimer(VignetteTimerHandle); 
		}
	}
}

void UPlayerStateComponent::UpdateVignetteOpacity()
{
	// í‹±ë§ˆë‹¤ Opacityë¥¼ ê°ì†Œì‹œí‚µë‹ˆë‹¤.
	DamageVignetteOpacity -= FApp::GetDeltaTime() / 1.0f; // 1.0fëŠ” ì „ì²´ ì§€ì† ì‹œê°„ (1ì´ˆ)
	DamageVignetteOpacity = FMath::Clamp(DamageVignetteOpacity, 0.0f, 1.0f);

	// Opacityê°€ 0ì— ë„ë‹¬í•˜ë©´ íƒ€ì´ë¨¸ë¥¼ ë©ˆì¶¥ë‹ˆë‹¤.
	if (DamageVignetteOpacity <= 0.0f)
	{
		GetWorld()->GetTimerManager().ClearTimer(VignetteTimerHandle);
	}
}

void UPlayerStateComponent::RevertMoveSpeed()
{
	MoveSpeed = PSR->MoveSpeed;
}

void UPlayerStateComponent::Multicast_PlayDamageUI_Implementation()
{
	// ì´ í•¨ìˆ˜ëŠ” ì„œë²„ì™€ ëª¨ë“  í´ë¼ì´ì–¸íŠ¸ì—ì„œ ì‹¤í–‰ë©ë‹ˆë‹¤.
    
	// í°ì„ í˜„ì¬ ë¡œì»¬ í”Œë ˆì´ì–´ê°€ ì œì–´í•˜ëŠ”ì§€ í™•ì¸í•©ë‹ˆë‹¤.
	// ë¦¬ìŠ¤ë‹ ì„œë²„ í˜¸ìŠ¤íŠ¸ì™€ ëª¨ë“  í´ë¼ì´ì–¸íŠ¸ì˜ í”Œë ˆì´ì–´ í°ì—ì„œë§Œ ì‹¤í–‰ë˜ì–´ì•¼ í•©ë‹ˆë‹¤.
	if (ACharacter* Char = Cast<ACharacter>(GetOwner()))
	{
		if (Char->IsLocallyControlled()) // ë¡œì»¬ í”Œë ˆì´ì–´ í°ì¼ ë•Œë§Œ UIë¥¼ ë„ì›€
		{
			// 1. Opacityë¥¼ ìµœëŒ€ì¹˜(1.0)ë¡œ ì„¤ì •
			DamageVignetteOpacity = 1.0f; 

			// 2. í‹± ì—†ì´ íƒ€ì´ë¨¸ë¡œ Opacityë¥¼ ë¶€ë“œëŸ½ê²Œ ê°ì†Œì‹œí‚¤ëŠ” í•¨ìˆ˜ í˜¸ì¶œì„ ì‹œì‘í•©ë‹ˆë‹¤.
			GetWorld()->GetTimerManager().SetTimer(
			   VignetteTimerHandle,
			   this,
			   &UPlayerStateComponent::UpdateVignetteOpacity,
			   0.016f, // ëŒ€ëµ 60FPSì˜ ë¸íƒ€ íƒ€ì„
			   true // ë£¨í”„ ì„¤ì •
			);
		}
	}
}

void UPlayerStateComponent::TakeDamage(float Amount)
{
	if (IsDead || IsKnocked) return;
	if (IsAttacked) return; // ê³µê²© ë°›ì€ í›„ ë¬´ì  ìƒíƒœ
	if (CurrentHP <= 0.f) Knocked();

	bCanRegenShield = false;
	GetWorld()->GetTimerManager().ClearTimer(RegenShieldTimer);
	GetWorld()->GetTimerManager().ClearTimer(bCanRegenShieldTimer);

	// ì´í™íŠ¸ë¥¼ ì¬ìƒí•˜ê¸° ì „ì— í˜„ì¬ ìºë¦­í„°ê°€ Authorityë¥¼ ê°€ì¡ŒëŠ”ì§€ í™•ì¸
	if (GetOwner()->HasAuthority())
	{
		Multicast_PlayDamageUI(); // ëª¨ë“  í´ë¼ì´ì–¸íŠ¸ì—ê²Œ UI ì¬ìƒì„ ëª…ë ¹
	}
	else
	{
		Server_RequestDamageUI(); // í´ë¼ì˜ ê²½ìš° ì„œë²„ì— UI ì¬ìƒ ìš”ì²­
	}
	
	// ì‰´ë“œê°€ ë‚¨ì•„ ìˆì„ ê²½ìš° ì‰´ë“œê°€ ë¨¼ì € ë°ë¯¸ì§€ë¥¼ ë°›ìŒ.
	if (CurrentShield > 0)
	{
		CurrentShield = FMath::Max(0.f, CurrentShield - Amount);
		UE_LOG(LogTemp, Warning, TEXT("Shield: %f"), CurrentShield);

	}
	else
	{
		CurrentHP = FMath::Max(0.f, CurrentHP - Amount);
		UE_LOG(LogTemp, Warning, TEXT("HP: %f"), CurrentHP);
	}

	GetWorld()->GetTimerManager().SetTimer(bCanRegenShieldTimer, this, &UPlayerStateComponent::EnableShieldRegen, 3.0f, false);
	
	if (CurrentHP <= 0.f) Knocked();
	else
	{
		// ê³µê²© ë‹¹í•œ ìƒíƒœë¡œ ì„¤ì •í•˜ê³  ë¬´ì  íƒ€ì´ë¨¸ ì‹œì‘
		IsAttacked = true;

		// 2ì´ˆ í›„ ë¬´ì  ìƒíƒœ í•´ì œ
		const float InvincibilityDuration = 1.0f;
		GetWorld()->GetTimerManager().SetTimer(InvincibilityTimerHandle, this, &UPlayerStateComponent::ResetInvincibility, InvincibilityDuration, false);
	}
}

void UPlayerStateComponent::Server_RequestDamageUI_Implementation()
{
	Multicast_PlayDamageUI();
}

void UPlayerStateComponent::EnableShieldRegen()
{
	bCanRegenShield = true;
	GetWorld()->GetTimerManager().SetTimer(RegenShieldTimer, this, &UPlayerStateComponent::RegenShieldHandle, PSR->ShieldRegenSpeed, true);
}

void UPlayerStateComponent::RegenShieldHandle()
{
	if (!bCanRegenShield || CurrentShield >= MaxShield || IsKnocked || IsDead)
	{
		GetWorld()->GetTimerManager().ClearTimer(RegenShieldTimer);
		return;
	}
	CurrentShield += 1.f;
	//UE_LOG(LogTemp, Log, TEXT("Shield Regen: %f"), CurrentShield);
}

void UPlayerStateComponent::Knocked()
{
	// Knocked ìƒíƒœ ë³€ê²½ì€ ì„œë²„ì—ì„œë§Œ ì‹¤í–‰
	if (!GetOwner()->HasAuthority()) Server_Knocked();
	
	UE_LOG(LogTemp, Error, TEXT("Player Knocked!"));
	
	IsKnocked = true;
	MoveSpeed = KnockedMoveSpeed;
	if (Character)
		Character->GetCharacterMovement()->MaxWalkSpeed = MoveSpeed;

	// ì„œë²„ëŠ” UIë¥¼ ë„ì›Œì•¼ í•˜ë¯€ë¡œ Multicast í˜¸ì¶œ
	// Multicast_PlayDamageUI(); // Knockedê°€ ë˜ì—ˆì„ ë•Œë„ UIë¥¼ ë„ì›ë‹ˆë‹¤.

	if (GetOwner()->HasAuthority())
	{
		UE_LOG(LogTemp, Error, TEXT("Player Knocked UI"));
		// ì¼ë°˜ ë°ë¯¸ì§€ UIì™€ ë™ì¼í•œ Multicastë¥¼ í˜¸ì¶œí•˜ì—¬ Opacityë¥¼ 1.0ìœ¼ë¡œ ë§Œë“­ë‹ˆë‹¤.
		Multicast_PlayKnockedUI(); 
	}
	
	// OnRep í•¨ìˆ˜ë¥¼ ìˆ˜ë™ìœ¼ë¡œ í˜¸ì¶œí•˜ì—¬ ì„œë²„ ìì‹ ì—ê²Œë„ ë¡œì§ì„ ì ìš©í•©ë‹ˆë‹¤.
	// OnRep_Knocked();
	
	// 5ì´ˆ ë’¤ Dead í•¨ìˆ˜ë¥¼ í˜¸ì¶œí•˜ëŠ” íƒ€ì´ë¨¸ë¥¼ ì„¤ì •
	GetWorld()->GetTimerManager().SetTimer(KnockedTimer, this, &UPlayerStateComponent::Dead, 15.0f, false);
}

void UPlayerStateComponent::Server_Knocked_Implementation()
{
	UE_LOG(LogTemp, Error, TEXT("Client Player Knocked!"));
	Knocked();
}

void UPlayerStateComponent::Dead()
{
	// Dead ìƒíƒœ ë³€ê²½ì€ ì„œë²„ì—ì„œë§Œ ì‹¤í–‰
	if (!GetOwner()->HasAuthority()) return;
	
	UE_LOG(LogTemp, Error, TEXT("Player Dead!"));
	IsKnocked = false;
	IsDead = true;
	MoveSpeed = DeadMoveSpeed;
	
	if (Character)
		Character->GetCharacterMovement()->MaxWalkSpeed = MoveSpeed;

	OnRep_Dead();

	// â–¼ í•œ ëª…ì´ë¼ë„ ì£½ìœ¼ë©´ ê²Œì„ì˜¤ë²„ ì•Œë¦¼
	if (ALudens_PGameMode* GM = GetWorld()->GetAuthGameMode<ALudens_PGameMode>())
	{
		GM->NotifyAnyPlayerDead();
	}
}

void UPlayerStateComponent::ResetInvincibility() 
{
	IsAttacked = false;
}

void UPlayerStateComponent::OnRep_IsAttacked()
{
	// í´ë¼ì´ì–¸íŠ¸ì—ì„œ í”¼ê²© ìƒíƒœ ë³€ê²½ ì‹œ ì²˜ë¦¬í•  ë¡œì§ (UI, ì´í™íŠ¸ ë“±)
}

void UPlayerStateComponent::OnRep_Dead()
{
	// í´ë¼ì´ì–¸íŠ¸ì—ì„œ ì£½ì€ ìƒíƒœ ë³€ê²½ ì‹œ ì²˜ë¦¬í•  ë¡œì§ (UI, ì´í™íŠ¸ ë“±)
	UE_LOG(LogTemp, Warning, TEXT("Client OnRep_Dead called."));
}

void UPlayerStateComponent::OnRep_Knocked()
{
	// í´ë¼ì´ì–¸íŠ¸ì—ì„œ ê¸°ì ˆ ìƒíƒœ ë³€ê²½ ì‹œ ì²˜ë¦¬í•  ë¡œì§ (UI, ì´í™íŠ¸ ë“±)
	UE_LOG(LogTemp, Warning, TEXT("Client OnRep_Knocked called."));

	// ë¡œì»¬ ì œì–´ í™•ì¸
	if (ACharacter* Char = Cast<ACharacter>(GetOwner()))
	{
		if (Char->IsLocallyControlled())
		{
			if (IsKnocked) // ğŸ’¥ ê¸°ì ˆ ìƒíƒœ ì‹œì‘ (True)
			{
				UE_LOG(LogTemp, Warning, TEXT("Player Knocked UI Play!!!!!"));
				// 1. Opacityë¥¼ ìµœëŒ€ ë¶ˆíˆ¬ëª…ë„(1.0)ë¡œ ê°•ì œ ì„¤ì •
				DamageVignetteOpacity = 1.0f; 
				// í˜¹ì‹œ ì‹¤í–‰ ì¤‘ì¼ì§€ ëª¨ë¥´ëŠ” 1ì´ˆ ë°ë¯¸ì§€ íƒ€ì´ë¨¸ë¥¼ í•´ì œí•˜ê³  ì¤‘ë‹¨
				GetWorld()->GetTimerManager().ClearTimer(VignetteTimerHandle);

				// 3. UI ë°”ì¸ë”©ì´ ì¦‰ì‹œ ì—…ë°ì´íŠ¸ë˜ë„ë¡ ê°•ì œ ì•Œë¦¼ (ì˜µì…˜, DOREPLIFETIMEì´ ì•„ë‹ˆë¯€ë¡œ ê°•ì œí•˜ì§€ ì•Šì•„ë„ í‹±ë§ˆë‹¤ ì—…ë°ì´íŠ¸ë¨)
				// ë§Œì•½ Opacityê°€ UPROPERTY(Replicated)ë¼ë©´ ì—¬ê¸°ì„œ OnRep_...ë¥¼ ìˆ˜ë™ í˜¸ì¶œí•˜ì§€ë§Œ, UI ë³€ìˆ˜ì´ë¯€ë¡œ ìƒëµí•©ë‹ˆë‹¤.
			}
			else // ê¸°ì ˆ ìƒíƒœ í•´ì œ (False)
			{
				// 1. ë¹„ë„¤íŠ¸ íš¨ê³¼ë¥¼ ì¦‰ì‹œ ì œê±°í•©ë‹ˆë‹¤.
				DamageVignetteOpacity = 0.0f;

				// 2. í˜¹ì‹œ Opacityë¥¼ 0.0ìœ¼ë¡œ ëŒë¦¬ëŠ” íƒ€ì´ë¨¸ê°€ ë‚¨ì•„ìˆì„ ìˆ˜ ìˆìœ¼ë¯€ë¡œ í•´ì œ (ì•ˆì „ ì¥ì¹˜)
				GetWorld()->GetTimerManager().ClearTimer(VignetteTimerHandle);
			}
		}
	}
}

void UPlayerStateComponent::OnRep_MoveSpeed()
{
	// í´ë¼ì´ì–¸íŠ¸ì—ì„œ MoveSpeed ê°’ì´ ë³µì œë˜ì—ˆì„ ë•Œ í˜¸ì¶œë¨.
	if (Character)
	{
		UE_LOG(LogTemp, Warning, TEXT("Client OnRep_MoveSpeed called. New Speed: %f"), MoveSpeed);
		Character->GetCharacterMovement()->MaxWalkSpeed = MoveSpeed;
	}
}

void UPlayerStateComponent::UpdateMoveSpeed()
{
	if (ACharacter* Char = Cast<ACharacter>(GetOwner()))
	{
		if (UCharacterMovementComponent* Move = Char->GetCharacterMovement())
		{
			Move->MaxWalkSpeed = MoveSpeed;
		}
	}	
}

void UPlayerStateComponent::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const
{
	Super::GetLifetimeReplicatedProps(OutLifetimeProps);
	
	DOREPLIFETIME(UPlayerStateComponent, MaxHP);
	DOREPLIFETIME(UPlayerStateComponent, CurrentHP);
	DOREPLIFETIME(UPlayerStateComponent, MaxShield);
	DOREPLIFETIME(UPlayerStateComponent, CurrentShield);
	DOREPLIFETIME(UPlayerStateComponent, IsAttacked);
	DOREPLIFETIME(UPlayerStateComponent, IsKnocked);
	DOREPLIFETIME(UPlayerStateComponent, IsDead);
	DOREPLIFETIME(UPlayerStateComponent, MoveSpeed);

	// ìƒì„± ìƒ‰ ë³µì œ ì¶”ê°€

	DOREPLIFETIME(UPlayerStateComponent, PlayerColor);
	DOREPLIFETIME(UPlayerStateComponent, bCanRegenShield); // ê²½ê³  í•´ì†Œ
}

static FORCEINLINE void OpApplyF(float& S, ERewardOpType Op, float V)
{
	if (Op == ERewardOpType::Multiply) S *= V; else S += V;
}

void UPlayerStateComponent::ApplyMaxHP(ERewardOpType Op, float V, ECurrentHPPolicy Policy)
{
	AActor* Owner = GetOwner();
	if (!(Owner && Owner->HasAuthority())) return;

	const float OldMax = MaxHP;
	const float OldCur = CurrentHP;

	OpApplyF(MaxHP, Op, V);
	MaxHP = FMath::Max(1.f, MaxHP);

	switch (Policy)
	{
	case ECurrentHPPolicy::KeepRatio: {
		const float Ratio = (OldMax > 0.f) ? (OldCur / OldMax) : 1.f;
		CurrentHP = FMath::Clamp(Ratio * MaxHP, 0.f, MaxHP);
	} break;
	case ECurrentHPPolicy::KeepCurrent: {
		CurrentHP = FMath::Clamp(CurrentHP, 0.f, MaxHP);
	} break;
	case ECurrentHPPolicy::HealToFull: {
		CurrentHP = MaxHP;
	} break;
	default: break;
	}

	// â˜… PSR ë°±ì—… ë™ê¸°í™”(ë¡œê·¸/ìœ„ì ¯ì—ì„œ PSRì„ ë´ë„ ì¼ì¹˜)
	if (PSR)
	{
		PSR->MaxHP = MaxHP;
		PSR->ForceNetUpdate();
	}

	// TODO: HP ë³€ê²½ ì´ë²¤íŠ¸/HUD ì•Œë¦¼ í•„ìš” ì‹œ ë¸Œë¡œë“œìºìŠ¤íŠ¸
}

void UPlayerStateComponent::ApplyMaxShield(ERewardOpType Op, float V, ECurrentHPPolicy Policy)
{
	AActor* Owner = GetOwner();
	if (!(Owner && Owner->HasAuthority())) return;

	const float OldMax = MaxShield;
	const float OldCur = CurrentShield;

	OpApplyF(MaxShield, Op, V);
	MaxShield = FMath::Max(0.f, MaxShield);

	switch (Policy)
	{
	case ECurrentHPPolicy::KeepRatio: {
		const float Ratio = (OldMax > 0.f) ? (OldCur / OldMax) : 1.f;
		CurrentShield = FMath::Clamp(Ratio * MaxShield, 0.f, MaxShield);
	} break;
	case ECurrentHPPolicy::KeepCurrent: {
		CurrentShield = FMath::Clamp(CurrentShield, 0.f, MaxShield);
	} break;
	case ECurrentHPPolicy::HealToFull: {
		CurrentShield = MaxShield;
	} break;
	default: break;
	}

	// â˜… PSR ë°±ì—… ë™ê¸°í™”
	if (PSR)
	{
		PSR->MaxShield = MaxShield;
		PSR->ForceNetUpdate();
	}
}

void UPlayerStateComponent::ApplyShieldRegenSpeed(ERewardOpType Op, float V)
{
	AActor* Owner = GetOwner();
	if (!(Owner && Owner->HasAuthority())) return;

	OpApplyF(PSR->ShieldRegenSpeed, Op, V);
	PSR->ShieldRegenSpeed = FMath::Clamp(PSR->ShieldRegenSpeed, 0.f, 10000.f);

	// í˜„ì¬ íƒ€ì´ë¨¸/í‹± ë¡œì§ì´ ì¬ìƒë¥ ì„ ì‚¬ìš©í•œë‹¤ë©´, ë‹¤ìŒ í‹±ë¶€í„° ë°˜ì˜ë˜ë„ë¡ ì—¬ê¸°ì„œ ë¦¬ì…‹/ê°±ì‹ 
	// ResetShieldRegenTimer();
}

void UPlayerStateComponent::SyncMoveSpeedFromPSR(APlayerState_Real* PS_R)
{
	if (!PSR) return;
	MoveSpeed = PSR->MoveSpeed;

	// í”„ë¡œì íŠ¸ êµ¬ì¡°ìƒ CalculateMoveSpeedê°€ ì†ŒìŠ¤ë¡œ ì“°ì´ë©´ ê°™ì´ ë§ì¶°ì¤ë‹ˆë‹¤.
	CalculateMoveSpeed = MoveSpeed;

	UpdateMoveSpeed();
}